from grobot import *

def start():
    drawString("Bereit",1,3)    
    delay(1000)
    drawString("3",1,3)
    delay(1000)
    drawString("2",1,4)
    delay(1000)
    drawString("1",1,5)
    delay(1000)

def displayAnweisungsText(spieler):
    drawString("Drehspiel",3,0)
    drawString("Spieler " + spieler + ",bitte",1,2)
    drawString("Gereat mit " + spieler ,1,3)
    drawString("nach oben",1,4)
    drawString("nehmen",1,5)
    
def spiel():
    drawString("LOS!!!!",4,4)
    playTone(500,500)
    delay(5000)
    drawString("Stop",1,4)
    playTone(500,500)
    
clearDisplay()
displayAnweisungsText("A")
drawString("A",0,7)
delay(5000)
clearDisplay()
drawString("Drehspiel",3,0)
drawString("A",0,7)
start()
motA.resetMotorCount()
clearDisplay()
drawString("Drehspiel",3,0)
drawString("A",0,7)
spiel()
drehwinkelA = motA.getMotorCount()
drawString(abs(drehwinkelA),0,6)
delay(4000)
drawString("Bitte geben",1,2)
drawString("Sie das Gereat",1,3)
drawString("an Spieler B.",1,4)
delay(10000)
clearDisplay()
drawString("Drehspiel",3,0)
drawString("B",17,7)
displayAnweisungsText("B")
delay(5000)
clearDisplay()
drawString("Drehspiel",3,0)
drawString("B",17,7)
start()
motB.resetMotorCount()
clearDisplay()
drawString("Drehspiel",3,0)
drawString("B",17,7)
spiel()
drehwinkelB = motB.getMotorCount()
drawString(abs(drehwinkelB),0,6)
delay(5000)
clearDisplay()
drawString("Resultat:",4,0)
drawString("A:"+str(abs(drehwinkelA)),2,2)
drawString("B:"+str(abs(drehwinkelB)),2,3)
delay(3000)
#vorzeichen ignorieren, if funktion rangliste
#Parabeln LED einbauen. Start einheitlich machen (def)
#spielerName()
