# ------------------------------------------------------------------
# Name  : WeatherLogger_00.py
# Source: https://raw.githubusercontent.com/walter-rothlin/Source-Code/master/Python_WaltisExamples/Code_05_DataLogger/WeatherLogger_00.py
#
# Description: Polling REST Service and write values to console
# https://openweathermap.org/current
#
# Autor: Walter Rothlin
#
# History:
# 06-Jul-2022   Walter Rothlin      Initial Version generated by Postman
# ------------------------------------------------------------------

import requests
import json


import requests

url = "https://api.openweathermap.org/data/2.5/weather?q=Uster&units=metric&lang=de&appid=144747fd356c86e7926ca91ce78ce170"

payload = { }
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

print("\n\nParses the response String and converts it to a JSON structutre (Dict-List-Dict...)")
responseStr = response.text
jsonResponse = json.loads(responseStr)

print("Show single fields!")
print("   Ortsname:", jsonResponse['name'])
print("   Land:", jsonResponse['sys']['country'])
print("   Temp:", jsonResponse['main']['temp'])
