#!/usr/bin/python

# ------------------------------------------------------------------
# Name  : WeatherLogger_01.py
# Source: https://raw.githubusercontent.com/walter-rothlin/Source-Code/master/Python_WaltisExamples/Code_05_DataLogger/WeatherLogger_01.py
#
# Description: Polling REST Service and write values to console
# https://openweathermap.org/current
#
# Autor: Walter Rothlin
#
# History:
# 06-Jul-2022   Walter Rothlin      Initial Version generated by Postman
# 03-Sep-2025   Walter Rothlin      Changes for HFU 2025
# 15-Jun-2025   Walter Rothlin      Refactored with HBU PY1
# ------------------------------------------------------------------

import json
import requests
import time
import datetime
import urllib.parse

class Weather_Station:
        def __init__(self,
                     appId,
                     town='Uster',
                     language='de',
                     units='metric',
                     service_provider='openweathermap',
                     end_point_url="https://api.openweathermap.org/data/2.5/weather"):


            self.__town = town
            self.__language = language
            self.__units = units
            self.__service_provider = service_provider
            self.__end_point_url = end_point_url
            self.__appId = appId


        def get_weather(self):
            params_end_point = {
                'appid': self.__appId,
                'q': self.__town,
                'units': self.__units,
                'lang': self.__language,
                'mode': '',  # xml, html
            }

            responseStr = requests.get(self.__end_point_url, params=params_end_point)
            jsonResponse = json.loads(responseStr.text)

            # repakage the response to a more compact format
            temp_unit = '°C'
            if self.__units == 'imperial':
                temp_unit = '°F'
            elif self.__units == 'standard':
                temp_unit = 'K'

            pressure_unit = 'hPa'

            weather_data = {
                "town": jsonResponse.get('name'),
                "country": jsonResponse.get('sys').get('country'),

                "temperature": {
                    "value": jsonResponse['main']['temp'],
                    "unit": temp_unit,
                    "string": f"{jsonResponse['main']['temp']}{temp_unit}",
                },
                "air_pressure": {
                    "value": jsonResponse['main']['pressure'],
                    "unit": pressure_unit,
                    "string": f"{jsonResponse['main']['pressure']}{pressure_unit}",
                },
                "humidity": {
                    "value": jsonResponse['main']['humidity'],
                    "unit": "%",
                    "string": f"{jsonResponse['main']['humidity']}%",
                },

                "coordinates": {
                    "lon": jsonResponse['coord']['lon'],
                    "lat": jsonResponse['coord']['lat']
                },

                "value": jsonResponse['weather'][0]['description'],
                "icon_url": f"http://openweathermap.org/img/w/{jsonResponse['weather'][0]['icon']}.png",

                "wind": {
                    "speed": {
                        "value": jsonResponse['wind']['speed'],
                        "unit": "m/s"
                    },
                    "direction": {
                        "value": jsonResponse['wind']['deg'],
                        "unit": "°"
                    }
                }
            }

            return weather_data

def getTimestamp(format='%Y-%m-%d %H:%M:%S'):
    return f'{datetime.datetime.now():{format}}'


if __name__ == "__main__":
    # User inputs specification
    ort_default = 'Wangen SZ'
    ort = input(f"Ort  [*{ort_default}]   :")
    if ort == "":
        ort = ort_default
    ort_encoded = urllib.parse.quote(ort)

    language_default = 'de'
    language = input(f"Sprache [*{language_default},el,en,fr,hr,it]:")
    if language == '':
        language = language_default

    units_default = "metric"
    units = input(f"Units [*{units_default},standard, imperial]:") or units_default


    wetterstation = Weather_Station(appId="144747fd356c86e7926ca91ce78ce170", town=ort, language=language, units=units)
    # print(wetterstation.get_weather())
    # print(wetterstation.get_weather().get("temperature").get("string"))



    # Logger config
    pollingTime = input("Polling-Time [s] (default 1): ") or "1"
    pollingTime = float(pollingTime)

    max_counter = input("Anzahl requests (default -1): ") or "-1"
    max_counter = int(max_counter)

    logFilename = input('Log-File Name:')

    log_delim = '|'

    firstTime = True
    counter = 0
    doLoop = True
    old_values_to_log = ''
    pinging = False
    while doLoop:
        counter += 1

        weather_data = wetterstation.get_weather()


        if firstTime:
            title_str = f"# File created: {getTimestamp()}, Data for {weather_data['town']} {weather_data['country']} ({weather_data['coordinates']['lon']}/{weather_data['coordinates']['lat']})"
            header_items = [
                "Timestamp          ",
                "Temp     ",
                "Druck           ",
                "Feuchtigkeit",
                "Wind                         ",
                "Beschreibung ",
                "Icon        ",
            ]

            header_str = log_delim.join(header_items)
            print(title_str)
            print(header_str)
            if logFilename != '':
                fHandler = open(logFilename, "a")
                fHandler.write(title_str + "\n" + header_str + "\n")
                fHandler.close()

        values_to_log = [
            f"{weather_data['temperature']['value']:>5}",
            f"{weather_data['temperature']['unit']:>3}",
            f"{weather_data['air_pressure']['value']:>10}",
            f"{weather_data['air_pressure']['unit']:>5}",
            f"{weather_data['humidity']['value']:>9}",
            f"{weather_data['humidity']['unit']:>2}",
            f"{weather_data['wind']['speed']['value']:>10}",
            f"{weather_data['wind']['speed']['unit']:>4}",
            f"{weather_data['wind']['direction']['value']:>10}",
            f"{weather_data['wind']['direction']['unit']:>2}",

            f"{weather_data['value']:>10}",
            f"{weather_data['icon_url']:>10}",
        ]
        log_str = log_delim.join(values_to_log)

        if old_values_to_log != log_str:
            old_values_to_log = str(log_str)
            if pinging:
                print()
            logStr = f'{getTimestamp()}{log_delim}{log_str}'
            print(logStr)
            if logFilename != '':
                fHandler = open(logFilename, "a")
                fHandler.write(logStr + "\n")
                fHandler.close()
        else:
            pinging = True
            print('.', end='', flush=True)

        time.sleep(pollingTime)
        firstTime = False
        if max_counter == -1:
            do_loop = True
        else:
            if counter >= max_counter:
                doLoop = False