# generated by ChatGPT on June, 15, 2023
# https://chat.openai.com/
# Dialog:
#    Generate a Python GUI Program with tkinter.
#    Could you rename the button to Walti?

import tkinter as tk

def greet():
    name = name_entry.get()
    greeting = "Hello, " + name + "!"
    greeting_label.config(text=greeting)

# Create the main window
window = tk.Tk()
window.title("Greeting App")

# Create and configure the name entry field
name_entry = tk.Entry(window, width=20)
name_entry.pack()

# Create and configure the greet button
greet_button = tk.Button(window, text="Walti", command=greet)
greet_button.pack()

# Create and configure the greeting label
greeting_label = tk.Label(window, text="")
greeting_label.pack()

# Start the main event loop
window.mainloop()